title: Data Science Indonesia
description: Welcome to our FunPage
show_downloads: false
google_analytics:
theme: jekyll-theme-cayman
github:
  is_project_page: true
  repository_url: https://github.com/datascienceid
